services:
  redis:
    image: redis:alpine3.19
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    sysctls:
      net.core.somaxconn: 1024
  database:
    image: postgres:13-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    security_opt:
      - no-new-privileges:true
    volumes:
      - tmp_data:/var/lib/postgresql/data

volumes:
  tmp_data: