services:
  proxy:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./frontend/nginx.dev:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - docker.internal.host:host-gateway
    depends_on:
      - api
  api:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - database
      - redis
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: database
      REDIS_URL: redis://redis:6379
      NODE_ENV: production
      PORT: 3000
  redis:
    image: redis:alpine3.19
    restart: unless-stopped
    sysctls:
      net.core.somaxconn: 1024
  database:
    image: postgres:13-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    security_opt:
      - no-new-privileges:true