-- Up Migration
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0015', 'Khóa Học Tiếng Anh Chuyên Ngành Y Khoa', 'paid', e'Dưới sự hướng dẫn của chúng tôi, bạn sẽ khám phá một khóa học đầy ý nghĩa và thiết thực, tập trung vào việc sử dụng tiếng Anh trong lĩnh vực y khoa và tương tác giao tiếp với bệnh nhân một cách chuyên nghiệp và nhạy cảm. Không chỉ là việc tiếp xúc với từ vựng và thuật ngữ y tế, mà còn là cơ hội để bạn phát triển kỹ năng giao tiếp nhân văn và sự nhạy cảm trong việc tương tác với các bệnh nhân đa dạng.

Trong suốt quá trình học, bạn sẽ được đào tạo qua các tình huống thực tế và kịch bản phỏng vấn, từ việc cung cấp thông tin y tế cho đến việc giải thích quy trình điều trị một cách đơn giản và tận tình. Bằng cách thực hành đối mặt với các tình huống khẩn cấp và xử lý các tình huống giao tiếp nhạy cảm, bạn sẽ tự tin hơn và trở nên chuyên nghiệp hơn trong việc tương tác với các bệnh nhân.

Không chỉ là việc nâng cao kỹ năng ngôn ngữ, mà khóa học này còn giúp bạn hiểu rõ hơn về tư duy y học và quy trình điều trị, từ đó giúp bạn trở thành một người chăm sóc sức khỏe toàn diện và có trách nhiệm. Hãy tham gia và trải nghiệm cách sử dụng tiếng Anh trong lĩnh vực y khoa một cách chuyên nghiệp và nhân văn.', 0, 'Advanced', 'https://listenandlearnenglish.com/wp-content/uploads/2020/06/Coffee-and-Objects-YouTube-Thumbnail.png', 'Học cách sử dụng tiếng Anh trong lĩnh vực y khoa và giao tiếp với bệnh nhân.', 'toeic', 390000, 'vnd', 'khoa-hoc-tieng-anh-chuyen-nganh-y-khoa-261783', 80, 0, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440018');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0050', 'Khóa Học Tiếng Anh Đàm Thoại', 'free', 'Khóa học này tập trung vào việc cải thiện khả năng đàm thoại tiếng Anh thông qua các tình huống giao tiếp hàng ngày và các hoạt động thảo luận.', 0, 'Intermediate', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYVLvs8Cg9a-u39IJCqXzqFWVfYH24SJh_96FUqbWqCA&s', 'Cải thiện khả năng giao tiếp hàng ngày bằng tiếng Anh.', 'conversation', 0, 'vnd', 'khoa-hoc-tieng-anh-dam-thoai', 40, 18, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440006');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0040', 'Khóa Học Tiếng Anh Hội Thoại Thương Mại', 'paid', 'Khóa học này tập trung vào việc phát triển kỹ năng hội thoại thương mại tiếng Anh thông qua các kịch bản và tình huống mô phỏng trong môi trường kinh doanh.', 0, 'Advanced', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6lamr1tQVS9nnmtZ8e2XzJEWmvqZFsG9XhqluNw29k26t_iTHGbkxyXsqH2QX2y7RyWs&usqp=CAU', 'Học cách thảo luận và giao tiếp trong môi trường kinh doanh.', 'business english', 320000, 'vnd', 'khoa-hoc-tieng-anh-hoi-thoai-thuong-mai', 60, 25, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440006');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0060', 'Khóa Học Tiếng Anh Học Thuật', 'paid', 'Khóa học này nhằm mục đích giúp bạn nắm vững vốn từ vựng và cấu trúc ngữ pháp tiếng Anh trong môi trường học thuật, từ viết báo cáo đến thảo luận seminar.', 0, 'Intermediate', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrgkjWZQjprs1B_Yl-Kb-J3EyziOV6tdpby_8Pcqme732R8tL1I5ukv-jKKY3IyZ4Xh7M&usqp=CAU', 'Nâng cao khả năng sử dụng tiếng Anh trong môi trường học thuật.', 'academic english', 280000, 'vnd', 'khoa-hoc-tieng-anh-hoc-thuat', 55, 30, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440013');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0011', 'Khóa Học Tiếng Anh Kỹ Năng Viết', 'free', e'Khóa học này không chỉ là một cơ hội để rèn luyện và nâng cao kỹ năng viết tiếng Anh của bạn mà còn là một hành trình sáng tạo và thú vị vào thế giới của văn chương và diễn đạt ý nghĩa. Tại đây, bạn sẽ được hướng dẫn qua các bài tập và thực hành, từ viết các đoạn văn ngắn đến việc phát triển các bài luận và bài viết chi tiết.

Mỗi bài học không chỉ tập trung vào việc nắm vững cấu trúc ngữ pháp và từ vựng phong phú, mà còn là một cơ hội để bạn khám phá và phát triển phong cách viết cá nhân của mình. Qua việc phân tích các mẫu văn bản và thảo luận về các kỹ thuật viết, bạn sẽ hiểu rõ hơn về cách tạo ra các câu chuyện hấp dẫn, thuyết phục độc giả và diễn đạt ý tưởng một cách sâu sắc.

Không chỉ là việc rèn luyện kỹ năng ngôn ngữ, mà khóa học này còn giúp bạn phát triển khả năng tư duy logic và sáng tạo trong việc xây dựng ý tưởng và trình bày bài viết của mình. Thông qua sự phản hồi từ giáo viên và các bạn học, bạn sẽ không ngừng hoàn thiện và tiến bộ trong việc viết tiếng Anh một cách tự tin và thành thạo.

Hãy tham gia vào hành trình này và trải nghiệm sự thăng tiến và hứng thú trong việc nâng cao kỹ năng viết tiếng Anh của bạn thông qua các bài tập và thực hành sáng tạo.', 0, 'Intermediate', 'https://img.freepik.com/free-vector/hand-drawn-english-lessons-twitter-header_23-2149286839.jpg?size=626&ext=jpg', 'Nâng cao kỹ năng viết tiếng Anh qua các bài tập và thực hành.', 'toeic', 0, 'usd', 'khoa-hoc-tieng-anh-ky-nang-viet-8193b', 60, 0, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440005');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0002', 'Khóa Học Tiếng Anh Cơ Bản', 'paid', e'Trong chương trình này, chúng ta sẽ khám phá cách sử dụng ngữ pháp cơ bản trong tiếng Anh và áp dụng nó vào giao tiếp hàng ngày. Không chỉ là việc học ngữ pháp trên giấy, mà chúng ta cũng sẽ tập trung vào việc sử dụng ngôn ngữ trong các tình huống thực tế, từ gặp gỡ và chào hỏi đến việc thảo luận và kể chuyện.

Chương trình này không chỉ đưa ra các quy tắc và cấu trúc ngữ pháp, mà còn tạo điều kiện để bạn áp dụng ngay những kiến thức đó vào các hoạt động thực hành. Thông qua các bài tập và kịch bản mô phỏng, bạn sẽ có cơ hội thực hành sử dụng ngữ pháp trong các tình huống giao tiếp hàng ngày, từ việc mô tả những sở thích cá nhân đến việc đặt câu hỏi về thời tiết.

Ngoài ra, chúng ta cũng sẽ xem xét các tình huống thực tế và phân tích cách sử dụng ngôn ngữ trong các cuộc trò chuyện hàng ngày. Bạn sẽ học cách phản ứng và đưa ra phản hồi một cách tự tin và tự nhiên trong các tình huống giao tiếp thường gặp, từ việc mua sắm đến tham gia vào các cuộc trò chuyện với bạn bè và đồng nghiệp.

Tham gia vào chương trình này và trải nghiệm cách sử dụng ngữ pháp cơ bản trong giao tiếp hàng ngày một cách linh hoạt và hiệu quả.', 0, 'Basic', 'https://img.freepik.com/free-vector/english-lessons-youtube-channel-art-flat-design_23-2149291621.jpg?size=626&ext=jpg', 'Học cách sử dụng ngữ pháp cơ bản và giao tiếp tiếng Anh hàng ngày.', 'ielts', 199999.99, 'vnd', 'khoa-hoc-tieng-anh-co-ban-93bf791', 50, 0, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440010');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0003', 'Khóa Học Tiếng Anh Giao Tiếp Sơ Cấp', 'free', e'Trong khóa học này, bạn sẽ được dẫn dắt qua một chương trình đào tạo sâu sắc và thực hành, tập trung vào việc nắm vững cách giao tiếp tiếng Anh cơ bản trong các tình huống hàng ngày. Thay vì chỉ là việc học ngữ pháp và từ vựng, chúng tôi đề cao việc phát triển khả năng giao tiếp tự tin và linh hoạt trong cuộc sống hàng ngày.

Thông qua các bài học thực tế và các kịch bản mô phỏng, bạn sẽ được rèn luyện trong các tình huống giao tiếp hàng ngày, từ việc gặp gỡ và chào hỏi đến việc mua sắm và đặt hàng trong cửa hàng. Bạn sẽ học cách đặt câu hỏi, thể hiện ý kiến và diễn đạt ý nghĩa của mình một cách rõ ràng và tự tin.

Ngoài ra, khóa học cũng tập trung vào việc phát triển kỹ năng lắng nghe và hiểu biết văn hóa, giúp bạn tương tác một cách nhạy cảm và hiệu quả với người bản xứ. Bạn sẽ học cách hiểu và sử dụng ngôn ngữ hàng ngày của tiếng Anh trong các tình huống thực tế, từ giao tiếp tại công viên đến tham gia vào các cuộc trò chuyện với bạn bè và đồng nghiệp.

Tham gia vào khóa học này và trang bị cho bản thân mình những kỹ năng cần thiết để giao tiếp một cách tự tin và thành công trong cuộc sống hàng ngày.', 0, 'Basic', 'https://img.freepik.com/premium-psd/learn-english-online-youtube-thumbnail-design-template_844516-269.jpg', 'Học cách giao tiếp tiếng Anh cơ bản trong các tình huống hàng ngày.', 'ielts', 0, 'vnd', 'khoa-hoc-tieng-anh-giao-tiep-so-cap-jfhb1', 20, 0, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440010');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0004', 'Khóa Học Tiếng Anh Phrasal Verbs', 'paid', e'Trong khóa học này, chúng ta sẽ thảo luận và thực hành cách sử dụng phrasal verbs một cách hiệu quả trong tiếng Anh. Thay vì chỉ nhớ các động từ và giới từ riêng lẻ, chúng ta sẽ khám phá cách kết hợp chúng để tạo ra các thành ngữ phức tạp và phong phú.

Chúng ta sẽ bắt đầu bằng việc hiểu rõ về cấu trúc và ý nghĩa của phrasal verbs, từ đó áp dụng chúng vào các tình huống thực tế. Thông qua các bài tập và ví dụ, bạn sẽ học cách sử dụng phrasal verbs trong giao tiếp hàng ngày, từ cuộc trò chuyện đến viết các văn bản.

Chúng ta cũng sẽ thảo luận về các chiến lược để nhớ và sử dụng phrasal verbs một cách linh hoạt và chính xác. Bằng cách thực hành và luyện tập, bạn sẽ cảm thấy tự tin hơn khi giao tiếp và viết bằng tiếng Anh, và sẽ có thể sử dụng phrasal verbs một cách tự nhiên và hiệu quả.', 0, 'Intermediate', 'https://img.freepik.com/free-vector/flat-english-lessons-social-media-cover-template_23-2149297566.jpg?size=626&ext=jpg', 'Học cách sử dụng phrasal verbs một cách hiệu quả trong tiếng Anh.', 'communication', 24.99, 'eur', 'khoa-hoc-tieng-anh-phrasal-verbs-13bf01', 40, 0, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440010');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0014', 'Khóa Học Tiếng Anh Ngữ Pháp Nâng Cao', 'paid', e'Trong khóa học này, chúng ta sẽ tiến xa hơn trong việc nắm vững và áp dụng ngữ pháp tiếng Anh nâng cao, và từ đó sử dụng nó một cách tự tin và hiệu quả trong việc viết và nói. Thay vì chỉ tập trung vào các quy tắc cơ bản, chúng ta sẽ đào sâu vào các khía cạnh phức tạp hơn của ngữ pháp và cách sử dụng chúng một cách linh hoạt.

Chúng ta sẽ bắt đầu bằng việc phân tích các cấu trúc ngữ pháp phức tạp và hiểu rõ về cách chúng hoạt động trong ngôn ngữ. Sau đó, chúng ta sẽ áp dụng những kiến thức này vào việc viết và nói thông qua các bài tập và thảo luận.

Không chỉ là việc rèn luyện kỹ năng viết, mà chúng ta cũng sẽ tập trung vào việc phát triển khả năng giao tiếp lưu loát và chính xác trong việc sử dụng ngữ pháp trong các cuộc trò chuyện và thảo luận. Bằng cách thực hành và luyện tập, bạn sẽ cảm thấy tự tin hơn khi sử dụng ngữ pháp nâng cao trong mọi tình huống giao tiếp và viết lách.', 0, 'Advanced', 'https://img.freepik.com/free-vector/gradient-english-lessons-youtube-thumbnai_23-2149285625.jpg', 'Nắm vững và áp dụng ngữ pháp tiếng Anh nâng cao trong việc viết và nói.', 'ielts', 34.99, 'usd', 'khoa-hoc-tieng-anh-ngu-phap-nang-cao-932hf', 60, 0, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440018');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0008', 'Khóa Học Tiếng Anh Phản Xạ', 'paid', e'Khóa học tiếng Anh này là một hành trình sâu sắc và thú vị vào thế giới của động từ phản xạ, một phần quan trọng của ngữ pháp tiếng Anh. Tại đây, bạn sẽ được dẫn dắt qua một chuyến phiêu lưu ngôn ngữ, khám phá cấu trúc, ý nghĩa và ứng dụng linh hoạt của động từ phản xạ trong cách diễn đạt của mình.

Khóa học này không chỉ đơn thuần là việc học về cấu trúc ngữ pháp, mà còn là một cơ hội để bạn hiểu sâu hơn về cách mà ngôn ngữ phản ánh lại cách chúng ta tương tác với thế giới xung quanh. Qua các bài giảng sinh động, ví dụ minh họa và bài tập thực hành, bạn sẽ khám phá cách sử dụng động từ phản xạ trong các tình huống thực tế, từ giao tiếp hàng ngày đến viết luận và thảo luận.

Không chỉ là việc rèn luyện kỹ năng ngôn ngữ, mà khóa học còn mang lại sự tự tin và linh hoạt trong việc sử dụng tiếng Anh một cách chính xác và truyền đạt ý nghĩa một cách hiệu quả. Bạn sẽ không chỉ học được cách sử dụng động từ phản xạ một cách chuyên nghiệp, mà còn hiểu rõ hơn về ngôn ngữ và văn hóa tiếng Anh thông qua việc thảo luận và tương tác với giáo viên và các bạn học.

Hãy tham gia vào hành trình này và khám phá sức mạnh của động từ phản xạ trong việc thể hiện ý nghĩa và tương tác ngôn ngữ một cách tự tin và tự nhiên.', 4.5, 'Intermediate', 'https://content.wepik.com/statics/9410580/preview-page0.jpg', 'Tìm hiểu về cấu trúc và sử dụng của động từ phản xạ trong tiếng Anh.', 'communication', 599999.99, 'vnd', 'khoa-hoc-tieng-anh-phan-xa-981hh', 30, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '90f5c3b5-6b82-4b6d-85b5-9c1d414e9a1f');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0005', 'Khóa Học Tiếng Anh Kinh Doanh', 'paid', e'Trong khóa học này, bạn sẽ tham gia vào một trải nghiệm học tập sâu sắc và thực tế, tập trung vào việc phát triển khả năng sử dụng tiếng Anh trong môi trường kinh doanh và các giao dịch quốc tế. Không chỉ là việc tiếp cận với từ vựng và thuật ngữ chuyên ngành, mà còn là cơ hội để bạn áp dụng những kiến thức đó vào thực tế thông qua các hoạt động thực hành và thảo luận.

Trải qua các kịch bản và tình huống mô phỏng, bạn sẽ rèn luyện kỹ năng giao tiếp trong các tình huống kinh doanh phức tạp, từ việc thương lượng hợp đồng đến việc xây dựng mối quan hệ đối tác đáng tin cậy. Không chỉ là việc nâng cao kỹ năng ngôn ngữ, mà còn là cơ hội để bạn hiểu rõ hơn về văn hóa kinh doanh và thực tiễn trong môi trường làm việc toàn cầu.

Bên cạnh đó, khóa học cũng mang đến kiến thức pháp lý và tài chính quan trọng để bạn có thể tự tin và hiệu quả hơn trong các giao dịch quốc tế. Tất cả những kiến thức và kỹ năng này sẽ giúp bạn trở thành một chuyên gia đáng tin cậy trong việc sử dụng tiếng Anh trong môi trường kinh doanh quốc tế, mở ra nhiều cơ hội mới và thành công trong sự nghiệp của bạn.', 5, 'Advanced', 'https://img.freepik.com/free-vector/flat-youtube-thumbnail-english-learning-lessons_23-2149255556.jpg', 'Học cách sử dụng tiếng Anh trong môi trường kinh doanh và giao dịch quốc tế.', 'communication', 302000, 'vnd', 'khoa-hoc-tieng-anh-kinh-doanh-28fh28', 70, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '90f5c3b5-6b82-4b6d-85b5-9c1d414e9a1f');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0012', 'Khóa Học Tiếng Anh Luyện Nghe', 'paid', e'Hãy tham gia vào một hành trình học tiếng Anh sôi động và đầy ý nghĩa, nơi bạn sẽ không chỉ nắm vững kỹ năng nghe mà còn khám phá thế giới thông qua những bài học thực tế và hấp dẫn. Khóa học này không chỉ là việc ngồi trong lớp học mà còn là một cuộc phiêu lưu mở cánh cửa đến văn hóa, xã hội và âm nhạc của các nước nói tiếng Anh.

Bằng cách tham gia vào các bài tập thú vị và hấp dẫn, bạn sẽ cải thiện khả năng nghe của mình một cách tự tin và linh hoạt. Từ việc lắng nghe các bản tin tin tức, các buổi phỏng vấn, đến việc thưởng thức nhạc và phim ảnh, bạn sẽ được đắm chìm vào ngôn ngữ một cách tự nhiên và dễ dàng hơn bao giờ hết.

Mỗi bài học không chỉ là việc lắng nghe và hiểu các đoạn văn nói một cách rõ ràng, mà còn là cơ hội để bạn trải nghiệm và thảo luận về những chủ đề thú vị, từ những vấn đề xã hội đến những câu chuyện cá nhân đầy cảm xúc. Bạn sẽ được thảo luận với giáo viên và các bạn học cùng lớp, từ đó xây dựng vốn từ vựng phong phú và kỹ năng giao tiếp mạnh mẽ.

Hãy tham gia vào khóa học này và trải nghiệm sự phong phú và đa dạng của tiếng Anh thông qua các hoạt động thực tế, từ cuộc trò chuyện hàng ngày đến các tình huống giao tiếp chuyên sâu. Hãy để tiếng Anh trở thành một phần của cuộc sống hàng ngày của bạn, không chỉ là một kỹ năng mà còn là một cánh cửa mở ra thế giới rộng lớn và đa dạng.


', 3, 'Intermediate', 'https://img.freepik.com/free-vector/flat-design-english-lessons-youtube-thumbnail-template_23-2149295935.jpg', 'Tập trung vào việc cải thiện khả năng nghe tiếng Anh thông qua các bài tập và bài nghe thực tế.', 'ielts', 147000, 'vnd', 'khoa-hoc-tieng-anh-luyen-nghe-83hw1', 30, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440013');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0009', 'Khóa Học Tiếng Anh Hội Thoại Du Lịch', 'paid', e'Trong chương trình này, bạn sẽ được tham gia vào một hành trình khám phá sâu sắc và thú vị, tập trung vào việc phát triển khả năng giao tiếp tiếng Anh trong các tình huống du lịch và khám phá văn hóa. Không chỉ là việc nắm vững từ vựng và cấu trúc ngôn ngữ phổ biến trong du lịch, mà còn là cơ hội để bạn trải nghiệm và thấu hiểu sâu hơn về các nền văn hóa đa dạng trên thế giới.

Thông qua các hoạt động thực hành và thảo luận, bạn sẽ rèn luyện kỹ năng giao tiếp trong các tình huống thực tế, từ việc hỏi đường đến việc đàm phán mua sắm và giao tiếp với người dân địa phương. Không chỉ là việc mở mang vốn từ vựng, mà còn là cơ hội để bạn tìm hiểu về phong tục tập quán và lối sống của các cộng đồng trên khắp thế giới.

Bên cạnh đó, chương trình cũng cung cấp thông tin hữu ích về điều kiện du lịch, an ninh và văn hóa để bạn có thể chuẩn bị tốt nhất cho các chuyến đi của mình. Tất cả những kỹ năng và kiến thức này sẽ giúp bạn trở thành một du khách tự tin và thông thạo trong việc giao tiếp tiếng Anh và khám phá văn hóa trên khắp thế giới.





', 2.5, 'Basic', 'https://img.freepik.com/free-vector/flat-english-lessons-youtube-thumbnail_23-2149266392.jpg', 'Học cách giao tiếp tiếng Anh trong các tình huống du lịch và khám phá văn hóa.', 'ielts', 400000, 'vnd', 'khoa-hoc-tieng-anh-hoi-thoai-du-lich-j3huf', 50, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440009');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0013', 'Khóa Học Tiếng Anh Giao Tiếp Thương Mại', 'paid', e'Chương trình này sẽ đưa bạn vào thế giới của giao tiếp tiếng Anh trong môi trường thương mại và giao dịch kinh doanh. Thay vì chỉ tập trung vào các tình huống giao tiếp hàng ngày, chúng ta sẽ khám phá cách sử dụng ngôn ngữ trong các bối cảnh chuyên nghiệp và doanh nghiệp.

Chúng ta sẽ bắt đầu bằng việc hiểu rõ về các thuật ngữ và ngôn ngữ chuyên môn trong lĩnh vực thương mại và kinh doanh. Sau đó, chúng ta sẽ thảo luận về cách áp dụng ngôn ngữ này vào các tình huống thực tế, từ việc thuyết phục đến đàm phán và thảo luận kinh doanh.

Không chỉ là việc rèn luyện kỹ năng ngôn ngữ, mà chúng ta cũng sẽ tập trung vào việc phát triển khả năng tư duy chiến lược và linh hoạt trong việc sử dụng ngôn ngữ trong môi trường kinh doanh. Bằng cách thực hành và thảo luận với các đồng nghiệp và giáo viên, bạn sẽ cảm thấy tự tin hơn khi tham gia vào các cuộc trò chuyện và giao dịch kinh doanh bằng tiếng Anh.', 5, 'Advanced', 'https://img.freepik.com/free-vector/flat-english-lessons-youtube-thumbnail_23-2149266357.jpg', 'Học cách giao tiếp tiếng Anh trong môi trường thương mại và giao dịch kinh doanh.', 'communication', 469000.99, 'vnd', 'khoa-hoc-tieng-anh-giao-tiep-thuong-mai-033hf', 70, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440009');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0006', 'Khóa Học Tiếng Anh Học Thuật', 'paid', e'Trong hành trình này, bạn sẽ được dẫn dắt vào thế giới của tiếng Anh trong lĩnh vực học thuật và nghiên cứu, nơi mà việc đọc, viết và nói tiếng Anh không chỉ là kỹ năng mà còn là công cụ cần thiết để thành công và phát triển sự nghiệp của bạn. Tại đây, chúng tôi không chỉ tập trung vào việc học từ vựng và cấu trúc ngữ pháp, mà còn là việc phát triển khả năng tự tin trong việc tham gia vào các cuộc trao đổi chuyên sâu và viết các bài báo, bài luận và bài thuyết trình chất lượng cao.

Qua các bài học và bài tập thực hành, bạn sẽ học cách đọc hiểu các văn bản học thuật, phân tích ý nghĩa và diễn đạt quan điểm của mình một cách rõ ràng và logic. Bạn cũng sẽ được hướng dẫn về cách viết các báo cáo, bài luận và bài thuyết trình có cấu trúc mạch lạc và hấp dẫn.

Ngoài ra, khóa học cũng tập trung vào việc phát triển kỹ năng giao tiếp trong môi trường học thuật, từ việc tham gia vào các cuộc thảo luận và hội thảo đến việc thuyết trình và phản biện. Bạn sẽ được trang bị những kỹ năng cần thiết để tự tin và thành công khi tương tác với cộng đồng học thuật quốc tế.

Hãy tham gia vào hành trình này và trở thành một chuyên gia trong việc sử dụng tiếng Anh trong lĩnh vực học thuật và nghiên cứu, mở ra những cơ hội mới và thành công trong sự nghiệp của bạn.', 4, 'Advanced', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREbg4mKmG5WsEh45TcZ331ju5HQ6DvT-S41c4ki3JzLg&s', 'Học cách đọc, viết và nói tiếng Anh trong lĩnh vực học thuật và nghiên cứu.', 'toeic', 34.99, 'usd', 'khoa-hoc-tieng-anh-hoc-thuat-jf21u', 60, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440006');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0007', 'Khóa Học Tiếng Anh Giao Tiếp Nâng Cao', 'paid', e'Trong chương trình này, chúng ta sẽ tiến xa hơn trong việc nâng cao kỹ năng giao tiếp tiếng Anh trong các tình huống phức tạp. Thay vì chỉ tập trung vào các tình huống giao tiếp đơn giản, chúng ta sẽ đào sâu vào những tình huống phức tạp và thách thức hơn, từ việc đàm phán và thuyết phục đến việc giải quyết xung đột và hiểu biết văn hóa.

Chúng ta sẽ bắt đầu bằng việc phân tích và hiểu rõ về các yếu tố tạo nên một tình huống giao tiếp phức tạp, bao gồm ngôn ngữ, cảm xúc và văn hóa. Sau đó, chúng ta sẽ thảo luận về các chiến lược và kỹ năng cần thiết để đối phó và thành công trong những tình huống này.

Không chỉ là việc rèn luyện kỹ năng ngôn ngữ, mà chúng ta cũng sẽ tập trung vào việc phát triển khả năng tư duy logic và linh hoạt trong việc xử lý các tình huống phức tạp. Bằng cách thực hành và thảo luận, bạn sẽ cảm thấy tự tin hơn khi đối mặt với các tình huống giao tiếp khó khăn và có thể tương tác một cách thành công trong mọi tình huống.', 3.5, 'Advanced', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWf59jREBPIoH66pIJFP7NqWzB-6WHEz4ptpzaZy1Qpg&s', 'Nâng cao kỹ năng giao tiếp tiếng Anh trong các tình huống phức tạp.', 'toeic', 799999.99, 'vnd', 'khoa-hoc-tieng-anh-giao-tiep-nang-cao-91kpa', 80, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440013');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0010', 'Khóa Học Tiếng Anh Phát Âm Chuẩn', 'paid', e'Hướng dẫn cách phát âm tiếng Anh chuẩn và cải thiện khả năng nghe hiểu. Điều này sẽ đưa bạn vào một hành trình phát âm tiếng Anh chuẩn và cải thiện khả năng nghe hiểu một cách tự tin và hiệu quả. Khóa học này không chỉ tập trung vào việc rèn luyện phát âm đúng và rõ ràng, mà còn cung cấp các chiến lược và kỹ thuật để bạn có thể hiểu rõ và phản ứng linh hoạt với nhiều loại giọng điệu và tốc độ khác nhau.

Thông qua các bài tập thực hành và phân tích các mẫu âm thanh, bạn sẽ học cách nhận biết và phát âm các âm tiếng Anh một cách chính xác, từ những âm cơ bản đến những ngữ điệu phức tạp hơn. Đồng thời, bạn cũng sẽ được hướng dẫn về cách luyện nghe và làm thế nào để nắm bắt thông tin từ các nguồn âm thanh khác nhau, từ cuộc trò chuyện hàng ngày đến các bài hát và podcast.

Không chỉ là việc luyện tập cá nhân, mà khóa học còn tạo điều kiện cho bạn thực hành giao tiếp và tương tác trong môi trường nhóm. Bạn sẽ được tham gia vào các hoạt động như thảo luận nhóm và trò chơi ngôn ngữ, giúp bạn tự tin hơn khi tiếp xúc với tiếng Anh trong mọi tình huống.

Tham gia khóa học này và khám phá cách cải thiện phát âm tiếng Anh và khả năng nghe hiểu của bạn một cách toàn diện và hiệu quả.', 2, 'Basic', 'https://cdn.eduadvisor.my/posts/2021/09/cg-english-feature.png', 'Hướng dẫn cách phát âm tiếng Anh chuẩn và cải thiện khả năng nghe hiểu.', 'toeic', 29.99, 'eur', 'khoa-hoc-tieng-anh-phat-am-chuan-913kf', 40, 1, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440006');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0020', 'Khóa Học Tiếng Anh Phát Âm Chuẩn', 'paid', 'Khóa học này sẽ giúp bạn cải thiện phát âm tiếng Anh của mình một cách đáng kể thông qua các bài tập và hoạt động thực hành chuyên sâu. Bạn sẽ được hướng dẫn từ những nguyên tắc cơ bản đến những kỹ thuật nâng cao nhất để phát âm chuẩn và tự tin.', 0, 'Intermediate', 'https://cdn.create.vista.com/downloads/bf530896-65f5-440c-a4d3-1c6da25e0f61_640.jpeg', 'Cải thiện phát âm tiếng Anh và tự tin giao tiếp.', 'pronunciation', 250000, 'vnd', 'khoa-hoc-tieng-anh-phat-am-chuan', 50, 20, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '90f5c3b5-6b82-4b6d-85b5-9c1d414e9a1f');
INSERT INTO public.courses (course_id, title, type, description, rating, level, thumbnail_url, headline, content_info, amount_price, currency, course_slug, access_count, total_students, created_at, updated_at, teacher_id) VALUES ('90f5c3b5-6b82-4b6d-85b5-9c1d414e0030', 'Khóa Học Tiếng Anh Viết Luận', 'free', 'Khóa học này tập trung vào việc phát triển kỹ năng viết luận tiếng Anh một cách chuyên sâu và hiệu quả. Bạn sẽ được hướng dẫn từ cấu trúc cơ bản đến việc viết các bài luận phức tạp và thuyết trình logic.', 0, 'Advanced', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWf59jREBPIoH66pIJFP7NqWzB-6WHEz4ptpzaZy1Qpg&s', 'Phát triển kỹ năng viết luận tiếng Anh.', 'writing', 0, 'vnd', 'khoa-hoc-tieng-anh-viet-luan', 35, 15, '2024-05-04 10:00:00.000000', '2024-05-04 10:00:00.000000', '550e8400-e29b-41d4-a716-446655440009');

-- Down Migration
DELETE FROM courses WHERE course_id IN (
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0015',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0050',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0040',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0060',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0011',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0002',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0003',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0004',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0014',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0008',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0005',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0012',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0009',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0013',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0006',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0007',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0010',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0020',
    '90f5c3b5-6b82-4b6d-85b5-9c1d414e0030'
);

